module.exports = [

  //隐藏的：
  //Python学习笔记
  //"post/STM32/Doxygen注释规范",
  //"post/STM32/STM32麦轮小车",
  //"post/活动策划/RM校内赛-前期策划",
  //"post/活动策划/报告书都要写些什么？",
  //"post/活动策划/无人驾驶比赛",
  //"post/活动策划/硬件模块",
  //"post/命令行/命令行基本操作"
  //"post/音乐/哥德堡变奏曲",
  //"post/音乐/不能说的秘密",
  //"post/美食/极简面包-烘培",
  //"post/言论/写作",
  //"post/言论/财富",
  //"post/言论/创业",
  //"post/言论/个人发展",
  {

    title: "电路设计",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/AirForce-充满灵性的电机驱动模块",
      "post/单片机最小系统设计—基于STM32（F1）",
      "post/SwiftCtrl-蓝牙手柄",
      "post/TinyDVR-小巧身材，满载动力",
      "post/ZenDriver-高性能的电机驱动",
      "post/PCB布线规范",
      "post/PCB元件布局规范",
      "post/函数思想在电路设计中的应用",
      "post/基本元器件选型",
      "post/电源的设计",
      "post/AD小技巧整理",
      "post/AD入门系列一：环境搭建",
      "post/AD入门系列二：基础知识",
      "post/AD入门系列三：原理图绘制",
      "post/AD入门系列四：PCB绘制",
      "post/AD入门系列五：库文件绘制",
      "post/自制CMSIS-DAP",
      "post/PCB名片设计",
      "post/AD使用Git的注意事项",
    ],
  },
  {
    title: "嵌入式开发",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/HAL系列教程1—GPIO",
      "post/PlatformIO—一站式嵌入式开发工具",
      "post/PlatformIO搭配CubeMX食用",
      "post/CubeMX的一些坑",
      "post/STM32的启动模式",
      "post/KeilMDK配置指南",
      "post/大疆N3飞控-参考资料",
      //"STM32模块设计-LED",
    ],
  },
  {
    title: "操作系统",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/Docker学习笔记",
      "post/CentOS配置OhMyZsh",
      "post/如何快速制作一个启动盘",
      "post/使用VSCode进行远程开发",
      //"Bash基础",
      //"Linux基础（CentOS）",
      //"从零搭建视觉开发环境（Docker-Linux）",
    ],
  },

  {
    title: "产品经理",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/产品经理的日常",
      "post/中台的概念",
      "post/画图基础",
      "post/智能硬件产品经理的技术要求",
      "post/如何撰写一份BRD",
      //"智能硬件产品开发流程",
    ],
  },


  {
    title: "Arduino",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/ATTiny85调试记录",
      "post/T-Clock桌上小钟",
      //"小车游华广-比赛",
      //"麦昆小车-测评",
      "post/一个舵机的自我修养",
      "post/麦轮小车",
    ],
  },

  {
    title: "树莓派",
    collapsable: false,
    sidebarDepth: 0,
    children: ["post/云打印服务器的搭建"],
  },
  {
    title: "前端",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/CSS学习笔记",
      "post/HTML学习笔记",
      "post/JavaScript学习笔记",
      "post/自适应网页设计",
      "post/Node.js和npm的安装与卸载（MacOS）",
      "post/前端开发-环境搭建",
    ],
  },
  {
    title: "微信小程序",
    collapsable: false,
    sidebarDepth: 0,
    children: ["post/BookJourney-二手书商城"],
  },

  {
    title: "Git&GitHub",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/Git学习笔记",
      "post/Git配置代理",
      "post/删除GitHub仓库中某个文件夹",
    ],
  },
  {
    title: "高效工作",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/用Vercel加速Pages服务",
      "post/文章排版规范",
      //"Excel批量激活链接并转换为图片",
      //"如何保存易逝的文字",
      "post/基于docsify搭建个人Wiki",
      "post/用Graphviz绘制关系图",
      "post/博客转至GitBook",
      "post/浅谈Bitcron博客平台",
      "post/RSS-高效率的阅读方式",
      "post/把回忆放心交给GooglePhotos",
      "post/构建知识管理系统",
      "post/回归博客",
      "post/定制SublimeText3",
      "post/VSCode生产力指南-环境配置",
      "post/VSCode生产力指南-JupyterNotebook",
      "post/在浏览器上运行VScode（code-server）",
      "post/如何配一台电脑",
      "post/用reveal.js制作幻灯片",
    ],
  },

  {
    title: "比赛经历",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      "post/THEHack2019",
      "post/Hack.init()",
      "post/焊接比赛：培训及总结",
    ],
  },
  {
    title: "生活方式",
    collapsable: false,
    sidebarDepth: 2,
    children: [
      //"华广爬楼指北",
      "post/读《黑客与画家》",
      "post/英语六级-备考",
      "post/谈谈未来的职业选择",
      //"科技X的访谈",
      "post/阅读书摘",
    ],
  },
  /*
  {
    title: "书摘",
    collapsable: true,
    sidebarDepth: 1,
    children: [
      "post/书摘/Producter",
      "post/书摘/且听风吟",
      "post/书摘/爱因斯坦的梦",
      "post/书摘/小岛经济学",
      "post/书摘/沉默的大多数",
      "post/书摘/黄金时代",
      "post/书摘/一只特立独行的猪",
      "post/书摘/王小波作品集（未归纳）",
      "post/书摘/关于审美",
      "post/书摘/创业时，我们在知乎聊什么",
      "post/书摘/游戏化教育：改变互联网教育的创新战略",
      "post/书摘/刘慈欣作品集",
      "post/书摘/博客十年",
      "post/书摘/失控",
      "post/书摘/生死疲劳",
      "post/书摘/沙与沫",
      "post/书摘/先知",
      "post/书摘/中国，少了一味药",
      "post/书摘/蝇王",
      "post/书摘/独裁者手册",
      "post/书摘/创造力：心流与创新心理学",
      "post/书摘/世界上有趣的事太多",
      "post/书摘/黑客与画家",
      "post/书摘/社会契约论",
      "post/书摘/天生有罪",
      "post/书摘/如何成为一个有趣的人",
      "post/书摘/当我谈跑步时我谈些什么",
      "post/书摘/百年孤独",
      "post/书摘/中国哲学史大纲",
      "post/书摘/东西文化及其哲学",
      "post/书摘/万历十五年",
      "post/书摘/乌合之众",
      "post/书摘/肖申克的救赎",
      "post/书摘/挪威的森林",
      "post/书摘/一个人的朝圣",
      "post/书摘/动物农场",
      "post/书摘/德米安：彷徨少年时",
      "post/书摘/基督山伯爵",
      "post/书摘/白鹿原",
      "post/书摘/活着",
      "post/书摘/岛上书店",
      "post/书摘/双城记",
      "post/书摘/一九八四",
      "post/书摘/万万没想到",
      "post/书摘/富爸爸，穷爸爸",
      "post/书摘/独裁者手册",
      "post/书摘/追风筝的人",
      "post/书摘/三体",
      "post/书摘/反脆弱：从不确定性中获益",
    ],
  },
  */

  {
    title: "友链",
    collapsable: false,
    sidebarDepth: 0,
    children: [
      ["https://bobi.site/", "BOBI83"],
      ["https://unbinilium.me", "Unbinilium"],
      ["https://waitech.cn/", "WAI 科技社"],
    ],
  },
];